Default: &defaults
  database: synciki.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: synciki_test.sqlite3
  <<: *defaults

Staging:
  database: synciki_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: synciki_production.sqlite3
  poolsize: 100
  <<: *defaults
